title: Welcome to the beginning of the time
author: The Great Almighty
email: kewal@think201.com
description: > # this means to ignore newlines until "baseurl:"
  Thinking of the beginning of time during this pandemic situation

# social links
twitter_username: kewalkris # DO NOT include the @ character, or else the build will fail!
github_username:  GreatAlmighty # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
